id: copy-router-config
summary: Copies Cisco configs via SNMP
description: This package copies configuration files from Cisco devices running SNMP.
categories:
- vuln-scan
homepage: https://www.offsec.com
size: 12288
install:
- provider: apt
  package: copy-router-config
  distros:
  - kali
  - debian
  - parrot
  - ubuntu
version: 1.0-1kali5
