"""Shell completion, generated from the parser that actually runs.

`argparse` gives none for free, and this CLI has about thirty subcommands with
their own flags -- the exact shape where completion stops being a nicety.

Generated by walking the live :func:`loadout.ui.cli.build_parser` rather than
maintained as three hand-written scripts, because a hand-written one goes
stale the first time somebody adds a flag and nothing fails when it does.

No new dependency: `shtab` does this well, but this project keeps its runtime
dependencies to three on purpose, and walking an `argparse` tree for names is
not worth a fourth.

Tool ids are deliberately *not* baked in. There are 842 of them, they change
with every catalog update, and a completion script carrying a stale copy would
confidently offer tools the catalog no longer has.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field

#: Shells this can emit for.
SHELLS = ("bash", "zsh", "fish")


@dataclass
class Command:
    """One subcommand: its name, its flags, and any subcommands of its own."""

    name: str
    help: str = ""
    options: list[str] = field(default_factory=list)
    children: list[Command] = field(default_factory=list)


def _options_of(parser: argparse.ArgumentParser) -> list[str]:
    found: list[str] = []
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            continue
        found.extend(action.option_strings)
    return sorted(dict.fromkeys(found))


def _subparsers_of(parser: argparse.ArgumentParser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def walk(parser: argparse.ArgumentParser) -> Command:
    """The parser as a plain tree, so emitters never touch argparse internals."""
    action = _subparsers_of(parser)
    children: list[Command] = []
    if action is not None:
        # `choices` holds one entry per alias pointing at the same parser;
        # `_choices_actions` keeps the canonical order and the help text.
        helps = {c.dest: (c.help or "") for c in action._choices_actions}
        for name, sub in action.choices.items():
            child = walk(sub)
            child.name = name
            child.help = helps.get(name, "")
            children.append(child)
    return Command(
        name=parser.prog or "loadout",
        options=_options_of(parser),
        children=children,
    )


def _bash(root: Command) -> str:
    names = " ".join(c.name for c in root.children)
    per_command = "\n".join(
        f"        {c.name}) opts='{' '.join(c.options)}'"
        f"{'; subs=' + repr(' '.join(g.name for g in c.children)) if c.children else ''} ;;"
        for c in root.children
    )
    return f"""# loadout bash completion. Generated by `loadout completions bash`.
_loadout() {{
    local cur prev words cword
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    local cmd="" sub="" opts="" subs=""
    local i
    for (( i=1; i < COMP_CWORD; i++ )); do
        case "${{COMP_WORDS[i]}}" in
            -*) continue ;;
            *) if [[ -z "$cmd" ]]; then cmd="${{COMP_WORDS[i]}}"; else sub="${{COMP_WORDS[i]}}"; fi ;;
        esac
    done

    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W "{names} {' '.join(root.options)}" -- "$cur") )
        return
    fi

    case "$cmd" in
{per_command}
        *) opts='' ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    elif [[ -n "$subs" && -z "$sub" ]]; then
        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    else
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    fi
}}
complete -F _loadout loadout
"""


def _zsh(root: Command) -> str:
    described = "\n".join(
        f"        '{c.name}:{_escape_zsh(c.help)}'" for c in root.children
    )
    per_command = "\n".join(
        f"        {c.name})\n"
        f"            _arguments {' '.join(_zsh_opt(o) for o in c.options) or ':'} ;;"
        for c in root.children
    )
    return f"""#compdef loadout
# loadout zsh completion. Generated by `loadout completions zsh`.
_loadout() {{
    local -a commands
    commands=(
{described}
    )

    _arguments -C '1:command:->command' '*::arg:->args'

    case $state in
        command) _describe -t commands 'loadout command' commands ;;
        args)
            case $words[1] in
{per_command}
            esac
        ;;
    esac
}}
compdef _loadout loadout
"""


def _zsh_opt(option: str) -> str:
    return f"'{option}[]'"


def _escape_zsh(text: str) -> str:
    return text.replace("'", "").replace(":", " -").strip()


def _fish(root: Command) -> str:
    lines = [
        "# loadout fish completion. Generated by `loadout completions fish`.",
        "complete -c loadout -f",
    ]
    for command in root.children:
        help_text = command.help.replace("'", "").strip()
        lines.append(
            f"complete -c loadout -n __fish_use_subcommand -a {command.name}"
            f" -d '{help_text}'"
        )
    for command in root.children:
        for option in command.options:
            lines.append(
                f"complete -c loadout -n '__fish_seen_subcommand_from {command.name}'"
                f" -l {option.lstrip('-')}"
                if option.startswith("--")
                else f"complete -c loadout -n '__fish_seen_subcommand_from {command.name}'"
                f" -s {option.lstrip('-')}"
            )
        for child in command.children:
            lines.append(
                f"complete -c loadout -n '__fish_seen_subcommand_from {command.name}'"
                f" -a {child.name}"
            )
    return "\n".join(lines) + "\n"


_EMITTERS = {"bash": _bash, "zsh": _zsh, "fish": _fish}


def render(shell: str, parser: argparse.ArgumentParser) -> str:
    """The completion script for *shell*."""
    key = shell.strip().lower()
    if key not in _EMITTERS:
        raise ValueError(f"unknown shell {shell!r}; expected one of {', '.join(SHELLS)}")
    return _EMITTERS[key](walk(parser))


#: Where each shell looks, for the hint printed alongside the script.
INSTALL_HINT = {
    "bash": "loadout completions bash > ~/.local/share/bash-completion/completions/loadout",
    "zsh": "loadout completions zsh > ~/.zfunc/_loadout   # ensure ~/.zfunc is in $fpath",
    "fish": "loadout completions fish > ~/.config/fish/completions/loadout.fish",
}
